# Generated by Django 4.2.3 on 2024-06-10 17:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_userprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="Internship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=255)),
                ("title", models.CharField(max_length=255)),
                ("image", models.ImageField(upload_to="internships/")),
                ("link", models.CharField(max_length=255)),
            ],
        ),
    ]
